const express = require('express')
const app = express()
const pug = require('pug')
const createRouter = require('./routers/create-route')
const depositRouter = require('./routers/deposit-route')
const loginRouter = require('./routers/login-route')
const registerRouter = require('./routers/register-route ')
const productRoute = require('./routers/product-route')
const authMiddleware = require('./middleware/auth-middleware')
const db = require('./db')
const bodyParser = require('body-parser')
const cookieParser = require('cookie-parser')
app.use(express.json())
app.use(express.urlencoded({ extended: true }))
app.set('view engine', 'pug')
app.use(cookieParser())
app.get('/', (req,res) => {
    res.render('home',{
        items: db.get('product').value()
    })
})
app.use(express.static('public'))
app.use('/create', createRouter)
app.use('/deposit',authMiddleware.auth, depositRouter)
app.use('/login', loginRouter)
app.use('/register', registerRouter)
app.use('/product', productRoute)
app.listen(8000, () => console.log('listening'))